[workspace]

members = ["opentable-monitor"]

[workspace.dependencies]

reqwest = { version = "0.12.3", features = ["json", "native-tls"], default-features = false }
tokio = { version = "1.37.0", features = ["full"] }